# Site settings
# These are used to personalize your new site.
# Some of these are required, optional or recommended
# "[]" are options to choose from
# Read more here: https://github.com/kristofk/podcast-template/wiki/Site-Properties

# RSS 2.0 Properties
title: EPodcast
description: An example on how to use this Podcast-template.
language: en
managingEditorName: 
managingEditorEmail: 
webMasterName: 
webMasterEmail: 
category: Technology
imageLinkType: relative
image: /assets/artwork.jpg

# iTunes Properties
itunesType: episodeic # recommended, [episodic/serial]
itunesSubtitle: A real example. # recommended
itunesSummary: An example on how to use this Podcast-template. # recommended
itunesAuthor: Kristof # recommended
itunesBlock: # [yes]
itunesCategory: Technology # recommended
itunesComplete: # [yes]
itunesExplicit: clean # recommended, [clean/explicit]
itunesImageLinkType: relative # [relative/absolute]
itunesImage: /assets/artwork.jpg # recommended
itunesNewFeedUrl:
itunesOwnerName: Kristof Kocsis # recommended
itunesOwnerEmail: appleContact@email.com # recommended

# Jekyll Properties
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Other info
email: epodcast@email.com # REQUIRED
twitter_username:
github_username: # A podcast usually isn't connected to Github, but since this is Jekyll, who knows.

# Build settings
permalink: /episodes/:slug
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
