# You can find more information about each property here: https://github.com/kristofk/podcast-template/wiki/Podcast-properties

# Channel properties
title:
description:
language:
category:
imageURL:
itunesExplicit:

# Other info
email:

# Jekyll properties
baseurl:
url:

# Build settings (only touch this if you know what you are doing)
permalink: /episodes/:slug
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed